# Generated by Django 4.1.4 on 2023-11-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydico', '0004_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='favorite_words',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='search_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
