# Generated by Django 4.1.4 on 2023-12-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydico', '0005_useraccount_favorite_words_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
